from app.routes import current_cart
from app import db
from app.models import db, Product

def rebuild_database():
    from app import db
    from app.models import db, Product

    db.drop_all()
    db.create_all()

    jekh = Product(image_file="/static/images/jeerakhakhara.png", name="Jeera Khakhara", size="500g", unit_price=4.00, category="khakharas")
    kmkha = Product(image_file="/static/images/kothmirmarchakhakhara.jpg", name="Kothmir Marcha Khakahra", size="500g", unit_price=4.00, category="khakharas")
    makh = Product(image_file="/static/images/masalakhakhra.jpg", name="Masala Khakhara", size="200g", unit_price=1.50, category="khakharas")
    jmkh = Product(image_file="/static/images/jeeramarikhakhra.jpg", name="Jeera Mari Khakhara", size="200g", unit_price=1.50, category="khakharas")
    sakh = Product(image_file="/static/images/sadakhakhra.jpg", name="Sada Khakhara", size="200g", unit_price=1.50, category="khakharas")
    acmkh = Product(image_file="/static/images/acharmasalakhakhra.jpg", name="Achar Masala Khakhara", size="200g", unit_price=1.50, category="khakharas")

    plpa = Product(image_file="/static/images/plainpapadi.jpg", name="Plain Papadi", size="9 OZ", unit_price=3.00, category="drysnacks")
    mapa = Product(image_file="/static/images/masalapapadi.ashx", name="Masala Papadi", size="9 OZ", unit_price=3.00, category="drysnacks")
    plse = Product(image_file="/static/images/plainsev.jpg", name="Plain Sev", size="12 OZ", unit_price=3.00, category="drysnacks")
    homi = Product(image_file="/static/images/hotmix.jpg", name="Hot Mix", size="12 OZ", unit_price=3.00, category="drysnacks")
    kmmi = Product(image_file="/static/images/khattamithamix.jpeg", name="Khatta Mitha Mix", size="12 OZ", unit_price=3.00, category="drysnacks")
    sumi = Product(image_file="/static/images/surtimix.jpg", name="Surti Mix", size="12 OZ", unit_price=3.00, category="drysnacks")
    pach = Product(image_file="/static/images/papadchavanu.jpg", name="Papad Chavanu", size="12 OZ", unit_price=3.00, category="drysnacks")
    mepa = Product(image_file="/static/images/methipara.jpg", name="Methi Para", size="12 OZ", unit_price=3.00, category="drysnacks")
    stga = Product(image_file="/static/images/stargathia.jpg", name="Star Ganthia", size="11 OZ", unit_price=3.00, category="drysnacks")
    bhga = Product(image_file="/static/images/bhavgathiya.png", name="Bhav Gathiya", size="12 OZ", unit_price=3.00, category="drysnacks")
    ph = Product(image_file="/static/images/phulvadi.jpg", name="Phulvadi", size="11 OZ", unit_price=3.00, category="drysnacks")
    bsbh = Product(image_file="/static/images/bikasevbhuji.jfif", name="Bikaneri Sev Bhujia", size="12 OZ", unit_price=3.00, category="drysnacks")
    rase = Product(image_file="/static/images/ratlamisev.jpg", name="Ratlami Sev", size="12 OZ", unit_price=3.00, category="drysnacks")
    rach = Product(image_file="/static/images/rajwadichevado.png", name="Rajwadi Chevado", size="12 OZ", unit_price=3.00, category="drysnacks")
    sspa = Product(image_file="/static/images/sweetsakarpara.jpg", name="Sweet Sakkar Para", size="11 OZ", unit_price=3.00, category="drysnacks")
    drka = Product(image_file="/static/images/drykachodi.jpg", name="Dry Kachori", size="11 OZ", unit_price=3.00, category="drysnacks")
    bh = Product(image_file="/static/images/bhakarwadi.jpg", name="Bhakarwadi", size="11 OZ", unit_price=3.00, category="drysnacks")
    vaga = Product(image_file="/static/images/vanelaganthiya.jpeg", name="Vanela Ganthia", size="12 OZ", unit_price=3.00, category="drysnacks")

    sh = Product(image_file="/static/images/shrikhand.jfif", name="Shrikhand", size="1 LB", unit_price=6.00, category="sweets")
    guja = Product(image_file="/static/images/gulabjamun.jpg", name="Gulab Jamun", size="12pcs", unit_price=4.00, category="sweets")
    ra = Product(image_file="/static/images/rasgulla.jpg", name="Rasgulla", size="8pcs", unit_price=4.00, category="sweets")
    chla = Product(image_file="/static/images/churmanuladoo.jpg", name="Churmanu Ladoo", size="1 LB", unit_price=6.00, category="sweets")
    ma = Product(image_file="/static/images/magaj.jpg", name="Magaj", size="14 OZ", unit_price=6.00, category="sweets")
    lusp = Product(image_file="/static/images/lunchspecial.jpg", name="Lunch Special", size="Rasmalai, Mutter Paneer, Dal Makhani, Samosa, Paratha, Jeera Rice, Pickles", unit_price=10.00, category="specials")
    ba = Product(image_file="/static/images/basundi.webp", name="Basundi", size="1 LB", unit_price=6.00, category="specials")
    bnbh = Product(image_file="/static/images/bhajinabhajiya.jpg", name="Bhaji na Bhajiya", size="8pcs", unit_price=4.00, category="specials")

    db.session.add(jekh)
    db.session.add(kmkha)
    db.session.add(makh)
    db.session.add(jmkh)
    db.session.add(sakh)
    db.session.add(acmkh)
    db.session.add(plpa)
    db.session.add(mapa)
    db.session.add(plse)
    db.session.add(homi)
    db.session.add(kmmi)
    db.session.add(sumi)
    db.session.add(pach)
    db.session.add(mepa)
    db.session.add(stga)
    db.session.add(bhga)
    db.session.add(ph)
    db.session.add(bsbh)
    db.session.add(rase)
    db.session.add(rach)
    db.session.add(sspa)
    db.session.add(drka)
    db.session.add(bh)
    db.session.add(vaga)
    db.session.add(sh)
    db.session.add(guja)
    db.session.add(ra)
    db.session.add(chla)
    db.session.add(ma)
    db.session.add(lusp)
    db.session.add(ba)
    db.session.add(bnbh)
    db.session.commit()
